// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	Data
	StoredData
*/
package messages

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Data struct {
	Icao             *string  `protobuf:"bytes,1,opt" json:"Icao,omitempty"`
	FlightNumber     *string  `protobuf:"bytes,2,opt" json:"FlightNumber,omitempty"`
	TransponderCode  *int32   `protobuf:"varint,3,opt" json:"TransponderCode,omitempty"`
	Altitude         *int32   `protobuf:"varint,4,opt" json:"Altitude,omitempty"`
	Speed            *int32   `protobuf:"varint,5,opt" json:"Speed,omitempty"`
	Heading          *int32   `protobuf:"varint,6,opt" json:"Heading,omitempty"`
	Latitude         *float64 `protobuf:"fixed64,7,opt" json:"Latitude,omitempty"`
	Longitude        *float64 `protobuf:"fixed64,8,opt" json:"Longitude,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}

func (m *Data) GetIcao() string {
	if m != nil && m.Icao != nil {
		return *m.Icao
	}
	return ""
}

func (m *Data) GetFlightNumber() string {
	if m != nil && m.FlightNumber != nil {
		return *m.FlightNumber
	}
	return ""
}

func (m *Data) GetTransponderCode() int32 {
	if m != nil && m.TransponderCode != nil {
		return *m.TransponderCode
	}
	return 0
}

func (m *Data) GetAltitude() int32 {
	if m != nil && m.Altitude != nil {
		return *m.Altitude
	}
	return 0
}

func (m *Data) GetSpeed() int32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *Data) GetHeading() int32 {
	if m != nil && m.Heading != nil {
		return *m.Heading
	}
	return 0
}

func (m *Data) GetLatitude() float64 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *Data) GetLongitude() float64 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

type StoredData struct {
	Time             *int64 `protobuf:"varint,1,req" json:"Time,omitempty"`
	Data             *Data  `protobuf:"bytes,2,req" json:"Data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *StoredData) Reset()         { *m = StoredData{} }
func (m *StoredData) String() string { return proto.CompactTextString(m) }
func (*StoredData) ProtoMessage()    {}

func (m *StoredData) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *StoredData) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}
